title: Srishti Jha # your name (or website title) here
logo: "https://i.ibb.co/BnjWSdS/Screenshot-2023-08-14-at-10-31-22-AM.png"
description: >
<a href = "mailto:jha.srishti@gmail.com">"Get in touch!"</a><br></br>

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
